sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        Xg3wO7ADFt2RbzO31/IqgJHp8EznqGrhB5UuOmLQFb0/Ww2L/YQlzx5d1bgfnVQK3B+b7zNE93KC1KAHB/i/d8XAeF14+6z+bt5N7EjCh8IZwZ45fI3JRg4imH6VjdcAvb33hS6U5EpDK7I+lM15k1yPqONBuDY07D693pRKpPlmLkhQO5Y1RGzR4Ss+f5Zrv9xFzyRq4+2zmw8L4HIk7SY0WG9XyfnUxLcSxID9RJReYYZjAyhxHzY1cGkD/67e6sx0Opq6LbpgA5e8cqyrhoQ7Q2HfuJ6XLbRZqVSPy/lZgikBdX4xsx+lQZBlJsrlPkGASVsmE+niW4mdJjUw3UwcBMtYo1JOLSKkMLjfGSfU+C7yBrGBmUpYenA5n/nOZo7GqI4xzWJYLxnhx4eYvbr7Fmukk3yI6MG9BG3kano2xHoXayGUrb1jts+bm8C0+PlMy3xI1/g/4Am8D6/Bg+RIaUAGspRx707+brBjVLPhV3wtA0lGCErrDzZfuHQ2R+wTGTlsBlkmU21y0SuHOOoG6Y8W7Ow1mXgHjmn63O8B1tdz6b31UfPU+qXcriioCVfd/UwxmLW6906BiSOLkavA/qKaE7xoizs9hzDYgXDSvboGy0csUsdP1qEJ/kHALyQI5wXzonR0aRBHsnb5+SH73wVV6FQVbxFqdMXgMP4=
    - secure: >-
        PwZ5U18NORTpRt7XPGv0koTRK8LdZshA7dwgy8X1xwdRUaILaxAU66JTQyCh4FNwmX0cy7h78wOCmGANeHqR0WgteNmfjAmaWQ3W5/X5umQJOIVMQ+KQnV62mQAykMXlzrws/WhlUt4Z2uoQs+HM6O0iB+c1fUfqcWaA3cE/URULh/t6QRc8uIopSqfTktKQBzNPtuWVjrOB/Y4uVcPYMYRySSp2fwsxKMa5ay3wSXaUL7SJvmqQhCLX9H2K8asrxK1MiZVipnzhFwULh1u4RAOtYvEXr3iiskYi1c2F7UusFmphfNgZeyuh6f/37ogZOBeQm/i8CdqtktCQeKvyvYJVuLTQWgqWAjFInoBRfjDODyXEchQ3YkkKmE1hW2rO6ZXHJ1sVNLnDHtaFZ8kfTPICLypMXwVHNv3PYNJH/WdGFU3mnu475ujZ70dg0+MjESTfhARswnAR8a9K9FUOyjE10jrWTVAE1LubCI3Dt7GNyOvmPLqS3zZ1bdhKD5unJnGv2C+ba+ygaoKzh90sHAmNpMExymzZYK9TuyUo+dueqpgFL2aQadRdgCYHn/Zbm4EXFVjpFSo1Ix+uTU1Os139rBGxDRD+R7sAhPBMAzldpFezpei+Jt2t1Y6r4NjynMBYQ7wuK8i6d91v/hP1NGEHz5f2uEolmzLt4Xou7sM=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
